const postResource = {
    vi: {
        header: "Đăng bất động sản",
        realestateType: "Loại hình bất động sản",
        postType: "Loại đăng tin",
        realestateName: "Tên khu dân cư, dự án",
        chooseProvince: "Chọn tỉnh thành",
        chooseDistrict: "Chọn quận/huyện",
        addressDetail: "Địa chỉ chi tiết",
        poster: "Bạn là",
        personal: "Cá nhân",
        agency: "Môi giới",
        title: "Tiêu đề",
        area: "Diện tích(m2)",
        price: "Giá(VND)",
        funiture: "Thông tin nội thất",
        numberOfBedRoom: "Số phòng ngủ",
        numberOfToilet: "Số phòng vệ sinh",
        numberOfFloor: "Số tầng",
        redBook: "Tình trạng sổ đỏ",
        hasRedBook: "Đã có sổ",
        noRedBook: "Chưa có sổ",
        selfContained: "Loại phòng trọ",
        private: "Khép kín",
        shard: "Chung chủ",
        floor: "Tầng thứ",
        legalDocument: "Giấy tờ pháp lý",
        noHave: "Không có",
        have: "Đã có sổ",
        pinkBook: "Sổ hồng riêng",
        landType: "Loại hình đất",
        description: "Mô tả",
        post: "Đăng tin",
        chooseFromMap: "Google map api",
        choosePosition: "Chọn vị trí từ bản đồ",
        dragFile: "Kéo thả tệp vào đây hoặc nhấn để chọn tệp",
        supportFile: "Hỗ trợ dịnh dạng *.png, *.jpg và kích thước tối đa 5MB",
        provideImage: "Cung cấp hình ảnh(Từ 4 hình ảnh trở lên)",
        addImage: "Thêm ảnh",
        removeImage: "Xóa ảnh"
    },
    en: {
        header: "Post real estate",
        realestateType: "Real estate type",
        postType: "Post type",
        realestateName: "Enter real estate name",
        chooseProvince: "Choose province",
        chooseDistrict: "Choose district",
        addressDetail: "Address detail",
        poster: "You are",
        personal: "Personal",
        agency: "Agency",
        title: "Title",
        area: "Area(m2)",
        price: "Price(VND)",
        funiture: "Funiture info",
        numberOfBedRoom: "Number of bed room",
        numberOfToilet: "Number of toilet",
        numberOfFloor: "Number of floor",
        redBook: "Red book status",
        hasRedBook: "Has red book",
        noRedBook: "No red book",
        selfContained: "",
        private: "",
        shard: ""
    }
}

export default postResource;